In [1]:
#Importing package numpy
import numpy as np

In [2]:
#Creating simple 1D array from a list
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [3]:
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
#Looking at different aspects of created array


#dimenssions with ndim method
print(arr.ndim)

#shape of the array with shape method
print(arr.shape)

#size of the array or total number of elements with size method
print(arr.size)

#No of bytes needs to move for changing position with strides method
print(arr.strides)

#type of the python object with type()
print(type(arr))

#memory location of the array with data method
print(arr.data)

2
(2, 5)
10
(40, 8)
<class 'numpy.ndarray'>


In [5]:
l = [1,2,3,4,5]
# l * 2
m = [w*2 for w in l]
m

[2, 4, 6, 8, 10]

In [6]:
l_arr = np.array([1,2,3,4,5])
print(l_arr * 2)

[ 2  4  6  8 10]


In [7]:
#Broadcasting of array elements for arithmatics

#Calculate BMI of cricket

#Heights of the players in inches 
height_inches = [61,65,63,69,70,73,68,64,63,62,66]

#Convert this to numpy array
ht_np = np.array(height_inches)

# ht_np
#Convert height from inch to meters by exposing it to 0.0245
ht_np = ht_np * 0.0245
ht_np

array([1.4945, 1.5925, 1.5435, 1.6905, 1.715 , 1.7885, 1.666 , 1.568 ,
       1.5435, 1.519 , 1.617 ])

In [8]:
#Weight of players in pounds
weight_pounds = [100,200,160,180,140,155,165,172,180,200,168]

#Convert this to numpy array
wt_np = np.array(weight_pounds)

#Convert weight from pounds to kgs by exposing it to 0.45
wt_np = wt_np * 0.45
wt_np

array([45.  , 90.  , 72.  , 81.  , 63.  , 69.75, 74.25, 77.4 , 81.  ,
       90.  , 75.6 ])

In [9]:
#BMI Calculation
# formula - bmi = weight in kgs / (height in meters ** 2)
bmi = wt_np / (ht_np ** 2)
bmi

array([20.1474773 , 35.48817184, 30.22172356, 28.3435777 , 21.41964658,
       21.80551373, 26.75139684, 31.48102353, 33.99943901, 39.0055999 ,
       28.91357251])

In [10]:
#Subsetting of arrays with index
bmi[0]

20.147477295192218

In [11]:
#Boolean based subsetting - try to get players with BMI less than 21
bmi[bmi < 21]
# bmi < 21

array([20.1474773])

In [12]:
#Slicing of arrays
bmi[0:3]

array([20.1474773 , 35.48817184, 30.22172356])

In [13]:
#Making 2D array with data from arrays we created for players where one row will be height and other will be weight
players = np.array([wt_np , ht_np])
players

array([[45.    , 90.    , 72.    , 81.    , 63.    , 69.75  , 74.25  ,
        77.4   , 81.    , 90.    , 75.6   ],
       [ 1.4945,  1.5925,  1.5435,  1.6905,  1.715 ,  1.7885,  1.666 ,
         1.568 ,  1.5435,  1.519 ,  1.617 ]])

In [14]:
#Looking at height and weight of the player at index 2
players[0][2],players[1][2]

(72.0, 1.5435)

In [15]:
#Looking at height of all the players, fetching height
players[1]

array([1.4945, 1.5925, 1.5435, 1.6905, 1.715 , 1.7885, 1.666 , 1.568 ,
       1.5435, 1.519 , 1.617 ])

In [16]:
#Transpose - lets transpose the array of players
pT = players.transpose()
pT.shape

(11, 2)

In [17]:
#Swap axes - Just like transpose but parameters needs to be defined explicitly - array and axes to be swapped
pT = np.swapaxes(pT,0,1)
pT.shape

(2, 11)

In [18]:
#Universal functions

#Unary functions

#arange and reshape
arr1 = np.arange(10).reshape(2,5)
print(arr1)

#square root function
arr2 = np.sqrt(arr1)
print(arr2)

#Exponential function
arr3 = np.exp(arr1)
print(arr3)

#Random number generator function
# arr4 = np.random.randn(10)
# print(arr4)

#Binary Functions - check the maximum out of two arrays
arr5 = np.maximum(arr2,arr3)
print(arr5)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0.         1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712 3.        ]]
[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
  5.45981500e+01]
 [1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
  8.10308393e+03]]
[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
  5.45981500e+01]
 [1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
  8.10308393e+03]]


In [19]:
#Mathematical and statistical functions

#mean function - find out mean of the weight of the players
print(np.mean(wt_np))

#median function - find out median of the weight of the players
print(np.median(wt_np))

#Sum function - find out sum of the weight of the players
print(np.sum(wt_np))

#standard devaition - find out standard deviation of the weight of the players
print(np.std(wt_np))

#Correlation coefficient - find out correlation between weight and height of the players
print(np.corrcoef(wt_np,ht_np))

74.45454545454545
75.60000000000001
819.0
12.082941667443528
[[ 1.         -0.01706933]
 [-0.01706933  1.        ]]


In [20]:
#Methods for boolean arrays
bools = [False,True,False,False,True]

b = np.array(bools)

#Sum method over boolean arrays
print(b.sum())

#any method
print(b.any())

#all method
print(b.all())

2
True
False


In [21]:
#Sort method

arr = np.random.randn(10).reshape(2,5)
print(arr)
print(np.sort(arr))

[[ 0.34169812  1.73728485 -0.23870477 -1.2940984   0.59864479]
 [ 0.51289288  0.0728758   0.70401938 -0.59839276  0.84636206]]
[[-1.2940984  -0.23870477  0.34169812  0.59864479  1.73728485]
 [-0.59839276  0.0728758   0.51289288  0.70401938  0.84636206]]


In [22]:
#Unique Function
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [23]:
#Ravel
arr4 = np.arange(10).reshape(2,5)
print(arr4)
rav1 = arr4.ravel()
print(rav1)
rav1[0] = 1000
print(rav1)
print(arr4)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
[1000    1    2    3    4    5    6    7    8    9]
[[1000    1    2    3    4]
 [   5    6    7    8    9]]


In [24]:
#Flatten
arr4 = np.arange(10).reshape(2,5)
print(arr4)
fl1 = arr4.flatten()
print(fl1)
fl1[0] = 1000
print(fl1)
print(arr4)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
[1000    1    2    3    4    5    6    7    8    9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [25]:
#Concatenation

ar1 = np.arange(10).reshape(2,5)
ar2 = np.arange(10).reshape(2,5)

print(np.concatenate([ar1,ar2], axis = 0))
print(np.concatenate([ar1,ar2], axis = 1))
print(np.vstack([ar1,ar2]))
print(np.hstack([ar1,ar2]))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4 0 1 2 3 4]
 [5 6 7 8 9 5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4 0 1 2 3 4]
 [5 6 7 8 9 5 6 7 8 9]]


In [26]:
#Split
arr = np.random.randn(5, 2)
print("Original array.")
print(arr)
print("\n")
first, second, third = np.split(arr, [1,2])
print("The first split")
print(first)
print("\n")
print("The second split")
print(second)
print("\n")
print("The third split")
print(third)
print("\n")

Original array.
[[ 0.50461231 -0.95602159]
 [-0.27006783 -0.66625578]
 [-0.3597419   0.87106225]
 [ 1.03575641 -0.32558643]
 [ 1.06933823 -0.62208904]]


The first split
[[ 0.50461231 -0.95602159]]


The second split
[[-0.27006783 -0.66625578]]


The third split
[[-0.3597419   0.87106225]
 [ 1.03575641 -0.32558643]
 [ 1.06933823 -0.62208904]]




In [27]:
#Repeat
arr = np.arange(3)
print(arr)
print("\n")
print(arr.repeat(4))

#We can pass list as argument for repeat
print("\n")
print(arr.repeat([2, 3, 4]))
print("\n")

#We can specify axes to do the repeat
arr_2 = np.random.randn(2, 2)
print(arr_2)
print("\n")
print(arr_2.repeat(2, axis=1))
print(arr_2.repeat(2, axis=0))

[0 1 2]


[0 0 0 0 1 1 1 1 2 2 2 2]


[0 0 1 1 1 2 2 2 2]


[[ 0.35235195  1.32454807]
 [ 0.29424332 -1.37867359]]


[[ 0.35235195  0.35235195  1.32454807  1.32454807]
 [ 0.29424332  0.29424332 -1.37867359 -1.37867359]]
[[ 0.35235195  1.32454807]
 [ 0.35235195  1.32454807]
 [ 0.29424332 -1.37867359]
 [ 0.29424332 -1.37867359]]


In [28]:
#Tile
print(np.tile(arr_2, 2)) #tiling at axis = 1 i.e. on columns
print("\n")
print(np.tile(arr_2, (2, 1))) #tiling on rows and columns 
print("\n")
print(np.tile(arr_2, (3, 2))) #tiling on rows and columns 

[[ 0.35235195  1.32454807  0.35235195  1.32454807]
 [ 0.29424332 -1.37867359  0.29424332 -1.37867359]]


[[ 0.35235195  1.32454807]
 [ 0.29424332 -1.37867359]
 [ 0.35235195  1.32454807]
 [ 0.29424332 -1.37867359]]


[[ 0.35235195  1.32454807  0.35235195  1.32454807]
 [ 0.29424332 -1.37867359  0.29424332 -1.37867359]
 [ 0.35235195  1.32454807  0.35235195  1.32454807]
 [ 0.29424332 -1.37867359  0.29424332 -1.37867359]
 [ 0.35235195  1.32454807  0.35235195  1.32454807]
 [ 0.29424332 -1.37867359  0.29424332 -1.37867359]]
